// The offline catalogue is a resilient fallback; normal rendering always uses the product API first.
const productImages=['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85'];
const products=[{id:1,name:'Running Shoes',category:'Shoes',price:1999,rating:4.5,reviews:128,originalPrice:2499,discount:20,isDeal:true},{id:2,name:'Classic Watch',category:'Accessories',price:1299,rating:5,reviews:94,originalPrice:1529,discount:15,isNew:true},{id:3,name:'Casual T-Shirt',category:'Clothes',price:799,rating:4.5,reviews:76,originalPrice:1141,discount:30,isDeal:true},{id:4,name:'Wireless Headphones',category:'Electronics',price:2499,rating:4.5,reviews:201,originalPrice:3048,discount:18},{id:5,name:'Denim Jeans',category:'Clothes',price:1499,rating:4,reviews:82},{id:6,name:'Leather Belt',category:'Accessories',price:599,rating:4,reviews:51},{id:7,name:'Sports Cap',category:'Accessories',price:399,rating:4.5,reviews:63},{id:8,name:'Sports Sneakers',category:'Shoes',price:2299,rating:4.5,reviews:112}].map((product,index)=>({...product,image:productImages[index]}));
let catalogue=[...products],currentCategory=new URLSearchParams(location.search).get('category')||'All';
const icon=c=>({Shoes:'👟',Clothes:'👕',Accessories:'⌚',Electronics:'🎧'})[c]||'🛍️',stars=r=>'★'.repeat(Math.floor(r||0))+'☆'.repeat(5-Math.floor(r||0)),money=n=>'₹'+Number(n||0).toLocaleString('en-IN'),normal=p=>({...p,id:p._id||p.id,reviews:p.reviewsCount??p.reviews??0});
const skeletons=(count,home=false)=>Array.from({length:count},()=>`<article class="skeleton-card ${home?'home-skeleton':''}"><div class="skeleton-media"></div><div class="skeleton-copy"><div class="skeleton-line short"></div><div class="skeleton-line title"></div><div class="skeleton-line short"></div><div class="skeleton-bottom"><div class="skeleton-line price"></div><div class="skeleton-circle"></div></div></div></article>`).join('');
const imageFor=p=>p.image?`<img class="product-photo" src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.classList.add('image-failed')">`:icon(p.category);
const badgeFor=p=>p.isNew?'New':p.discount?'Sale':p.isFeatured?'Bestseller':'';
function wishButton(p){return `<button class="wish-button ${NexCart.wishlist().some(x=>String(x.id)===String(p.id))?'is-saved':''}" data-wish="${p.id}" aria-label="Save ${p.name} to wishlist">♡</button>`}
function attachCardControls(box){box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add,b));box.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>{const p=catalogue.find(x=>String(x.id)===String(b.dataset.wish));if(!p)return;const saved=NexCart.toggleWish(p);b.classList.toggle('is-saved',saved);b.innerHTML=saved?'♥':'♡'});}
function cardMarkup(p,n,home=false){const badge=badgeFor(p),old=p.originalPrice?`<del>${money(p.originalPrice)}</del>`:'';return `<article class="${home?'product-card':'store-product-card'}"><div class="${home?'product-image image-'+['one','two','three','four'][n%4]:'store-product-image store-image-'+(n%6+1)}">${imageFor(p)}${badge?`<span class="${home?'sale-badge':'store-sale'}">${badge}</span>`:''}${wishButton(p)}</div><div class="${home?'product-info':'store-product-info'}"><div class="${home?'category':'store-category'}">${p.category==='Clothes'?'Fashion':p.category}</div><h3><a href="product-details.html?id=${p.id}">${p.name}</a></h3><div class="${home?'rating':'store-rating'}">${stars(p.rating)} <span>(${p.reviews})</span></div><div class="${home?'product-bottom':'store-product-bottom'}"><span><strong class="${home?'':'store-price'}">${money(p.price)}</strong>${old}</span><button ${home?'':'class="add-cart"'} data-add="${p.id}" aria-label="Add ${p.name} to cart">🛒</button></div></div></article>`}
function displayProducts(list){const box=document.getElementById('products-container'),count=document.getElementById('product-count'),empty=document.getElementById('no-results');if(!box)return;box.innerHTML=list.map((p,n)=>cardMarkup(p,n)).join('');count.textContent=list.length;empty.style.display=list.length?'none':'block';attachCardControls(box)}
function filtered(){let list=catalogue,term=(document.getElementById('product-search')?.value||new URLSearchParams(location.search).get('search')||'').trim().toLowerCase(),min=Number(document.getElementById('min-price')?.value||0),max=Number(document.getElementById('max-price')?.value||0),rating=Number(document.getElementById('rating-filter')?.value||0),sort=document.getElementById('sort-filter')?.value||'featured';if(currentCategory==='New')list=list.filter(p=>p.isNew);else if(currentCategory==='Deals')list=list.filter(p=>p.isDeal||p.discount);else if(currentCategory!=='All')list=list.filter(p=>p.category===currentCategory);if(term)list=list.filter(p=>[p.name,p.category,p.brand,...(p.tags||[])].filter(Boolean).join(' ').toLowerCase().includes(term));if(min)list=list.filter(p=>p.price>=min);if(max)list=list.filter(p=>p.price<=max);if(rating)list=list.filter(p=>(p.rating||0)>=rating);list=[...list];if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='rating-desc')list.sort((a,b)=>(b.rating||0)-(a.rating||0));displayProducts(list)}
function addToCart(id,button){const p=catalogue.find(x=>String(x.id)===String(id));if(!p)return;NexCart.add(p);if(button){button.classList.add('add-success');const original=button.textContent;button.textContent='✓';setTimeout(()=>{button.textContent=original;button.classList.remove('add-success')},800)}}
async function loadProducts(){const box=document.getElementById('products-container');if(box)box.innerHTML=skeletons(8);try{const result=await api.get('/products'+location.search);catalogue=result.products.map(normal)}catch(e){}filtered()}
async function loadHomeProducts(){const box=document.getElementById('home-products');if(!box)return;box.innerHTML=skeletons(4,true);try{const result=await api.get('/products?limit=4&sort=-rating');catalogue=result.products.map(normal)}catch(e){}box.innerHTML=catalogue.slice(0,4).map((p,n)=>cardMarkup(p,n,true)).join('');attachCardControls(box)}
document.addEventListener('DOMContentLoaded',()=>{const box=document.getElementById('products-container');if(box){document.querySelectorAll('.filter-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentCategory=b.dataset.category;filtered()});const match=[...document.querySelectorAll('.filter-btn')].find(b=>b.dataset.category===currentCategory);if(match){document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));match.classList.add('active')}document.getElementById('search-button')?.addEventListener('click',filtered);document.getElementById('product-search')?.addEventListener('keydown',e=>e.key==='Enter'&&filtered());['min-price','max-price','rating-filter','sort-filter'].forEach(id=>document.getElementById(id)?.addEventListener(id.includes('price')?'input':'change',filtered));document.getElementById('clear-filters')?.addEventListener('click',()=>{['min-price','max-price'].forEach(id=>document.getElementById(id).value='');document.getElementById('rating-filter').value='0';document.getElementById('sort-filter').value='featured';filtered()});loadProducts()}else loadHomeProducts()});
